package:
  name: my_package
  version: "1.0.0"

source:
  git_rev: "1.0.0"
  git_url: https://github.com/crabtr26/anaconda-docker.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - my_package

about:
  home: https://github.com/crabtr26/anaconda-docker