[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
asyncio_mode="auto"
testpaths = [
    "tests"
]
addopts = "-rf -vv --cov=src/ --cov-report=term-missing"
